### PR TITLE
add editable multi select example

### PR DESCRIPTION
**Pull request by slavab89**
**What**: Add a multi editable select tags example

**Checklist**:
- [X] Documentation
- [ ] Tests - N/A
- [X] Ready to be merged
- [ ] Added myself to contributors table

In case some changes need to be made in the example, please let me know.
I'm not sure if its somehow possible to make the example editable by other people (In case something needs to be fixed / changed in the example in the future).. Or we'll just need to put a different link.

### CODE REVIEW

**Comment by mikeebee** [comment]
Hey @slavab89 / @kentcdodds. This example doesn't appear to be working for creation of new tags. The selection works fine but when I type something and press enter, nothing happens.

Any ideas?

**Comment by kentcdodds** [comment]
That's because the example doesn't support enter, only tab. I've added enter support here. Was a pretty simple addition to `MultiDownshift.js` and I've added a comment to call it out :)

https://codesandbox.io/s/pk0kv34zm7

**Comment by mikeebee** [comment]
Haha solid comment in that file, Sir! :D 

Thanks for that! Out of curiosity, was there a particular reason for favouring tab over enter? I'd not seen that as a convention for things like this.

**Comment by kentcdodds** [comment]
I didn't make the example, but I'm assuming it's so the enter key can submit the form or something 🤷‍♂️ 

Could probably have both though (ie only use `event.preventDefault()` if the menu is open).

**Comment by mikeebee** [comment]
Yeah I _think_ that's what most users would expect. Thanks for getting back to me, and thanks @slavab89 for the example.

**Comment by slavab89** [comment]
😄 Just wanted to show an example of how to use it but yeah i believe Enter should be actionable as it seems natural to me.
btw, the example is not really updated to the latest version of the library and quite a lot has changed since (22+ versions) so the whole implementation may somewhat change based on new features and fixes.

@kentcdodds I saw that there are stories as well, should i try to migrate that example to a story (while basing the structure and solution on your other more recent examples?)

**Comment by kentcdodds** [comment]
The stories are also useful examples, the problem is that it's harder for people contribute to and "fork" those examples and make changes to them than if we use codesandbox. So I prefer codesandbox generally.

**Pull request merged**
