### PR TITLE
fix: check if composite component uses forwardRef

### PR DESCRIPTION
**Pull request by akronb**
**What**:
Remove 'refKey' warning for elements witch use forwardRef (#604). Changed `getRootProps` properties in documentation from required to optional.

**Why**:

**How**:

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged
      
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by akronb** [comment]
I added tests, but Travis build is failing. I'm gonna try to fix this today.

**Comment by akronb** [comment]
As i understand it, `rollup-plugin-commonjs` causes the problem and can be resolved by [adding namedExports](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports) in rollup config.

If you wanted me to open PR in `kcd-scripts` to fix it, i can do it.

**Comment by kentcdodds** [comment]
We can create a custom rollup config for this project:

```javascript
// rollup.config.js
const commonjs = require('rollup-plugin-commonjs')
const config = require('kcd-scripts/dist/config/rollup.config.js')

const cjsPluginIndex = config.plugins.findIndex(plugin => plugin.name === 'commonjs')
config.plugins[cjsPluginIndex] = commonjs({include: 'node_modules/**', /* extra config here */})

module.exports = config
```

I think that should be fine :)

**Pull request merged**
