### PR TITLE
[#23] Flow definitions

### PR DESCRIPTION
**Pull request by stereobooster**
**What**: added script to generate flow definitions
**Why**: because people use downshift with Flow
**How**: flowgen generates type definitions from TypeScript definitions
**Checklist**:

* [ ] Documentation
* [ ] Tests
* [ ] Ready to be merged
* [ ] Added myself to contributors table

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hey thanks! This seems great! Though honestly it doesn't seem like it would be all that hard to maintain them separately considering how small the API surface is 🤔 If these bugs give us a lot of trouble I'd rather do that. Luckily for us your PR has given us a great place to start! Would by be opposed to just doing that instead?

**Comment by stereobooster** [comment]
> Though honestly it doesn't seem like it would be all that hard to maintain them separately

You mean inside https://github.com/flowtype/flow-typed?

Current state of flowtype tooling is sad, it is not optimised for developers workflow. I would prefer to keep definitions here (if this is possible, I also would understand if you do not want it)

> If these bugs give us a lot of trouble

The only issue is this with `kcd-scripts`. Other one I want to fix

**Comment by kentcdodds** [comment]
The `kcd-scripts` error says:

```
[error] typings/index.flow.js: SyntaxError: `declare export interface` is not supported. Use `export interface` instead (9:16)
[error]    7 |  */
[error]    8 |
[error] >  9 | declare export interface DownshiftState {
[error]      |                ^
[error]   10 |     highlightedIndex: number | null,
[error]   11 |         inputValue: string | null,
[error]   12 |         isOpen: boolean,
```

It's not a kcd-scripts error at all, it looks to be a prettier error. We could probably add that file to [the `.prettierignore` file](https://github.com/paypal/downshift/blob/f6e838b924ca8c9c207ca04154d07c11d76dfad1/.prettierignore) and avoid that error (though that means it wont be formatted by prettier, but as it is that's the case anyway).

I wasn't suggesting flow-typed. I was just suggesting that rather than generating the types we maintain them by hand. Considering they're so small I don't know whether it's worth making the tooling work.

If we _do_ want to go with the generated approach, then I'll want the generation of the flow types to happen as part of the precommit hook. I can help make that happen because it takes a little bit of understanding of how kcd-scripts works. But I still think that maintaining them completely separately is preferrable...

**Comment by stereobooster** [comment]
> I wasn't suggesting flow-typed. I was just suggesting that rather than generating the types we maintain them by hand. Considering they're so small I don't know whether it's worth making the tooling work.

Ah I see. I have no preference. As soon as we get through with TypeScript update (https://github.com/paypal/downshift/pull/373) I will update this PR

> It's not a kcd-scripts error at all, it looks to be a prettier error. 

This is strange, I was sure Prettier can eat any flow file. I will double check this

**Comment by kentcdodds** [comment]
Thanks for all your help @stereobooster! You're a rock star!

giphy

**Comment by stereobooster** [comment]
This doesn't work so far. I asked for advice in flow channel, but no luck so far

**Comment by stereobooster** [comment]
closed in favour https://github.com/paypal/downshift/pull/399

**Pull request closed without merging**
