### PR TITLE
chore(tooling): update kcd-scripts

### PR DESCRIPTION
**Pull request by Andarist**
**Motivation**
https://github.com/kentcdodds/kcd-scripts/pull/71

### CODE REVIEW

**Comment by Andarist** [comment]
UMD
```js
 function _objectWithoutPropertiesLoose(source, excluded) {
  // ...
}

  function _extends() {
  // ..
  }
```

ESM
```js
import computeScrollIntoView from 'compute-scroll-into-view';
import _objectWithoutPropertiesLoose from '@babel/runtime/helpers/esm/objectWithoutPropertiesLoose';
import _extends from '@babel/runtime/helpers/esm/extends';
import _inheritsLoose from '@babel/runtime/helpers/esm/inheritsLoose';
import _assertThisInitialized from '@babel/runtime/helpers/esm/assertThisInitialized';
import React, { Component } from 'react';
import PropTypes from 'prop-types';
```

**Comment by Andarist** [comment]
Tests are wrongly configured though (might be because of kcd-scripts upgrade) - gonna take a look soon & ping you once I fix it.

**Comment by kentcdodds** [comment]
Thanks!

**Comment by Andarist** [comment]
Quick question - because it seems it might take me more time than just asking, as I don't know how particular test works. The problem is about `test:build` which validates the shape of the exported bundles.

It tries to:
```js
import esImport from '../../../dist/downshift.esm'
```

**Comment by Andarist** [comment]
Failing test fixed by https://github.com/paypal/downshift/pull/600/files#diff-bdf18ce84c0e58ae0430b02003fee4dbR7 , cc @kentcdodds

**Pull request merged**
