### PR TITLE
scrollIntoView bugs

### PR DESCRIPTION
**Pull request by Drapegnik**
**What**:
1. Cross browser support `.scrollTop`
2. Fix `scrollIntoView` method in some corner cases

**Why**:
1. The problem is that different browsers apply global scroll to different 
elements:
    
    * **Chrome**:
    chrome
     
    * **Safari**:
     safari

    So, when `closestScrollParent` is `body`, in Chrome, `body.scrollTop` returns 0

2. Second problem is the following: when parent element is "bigger" than current `View` area `scrollParentRect.top` is negative, and method works incorrect
     
    bug

    So, it leads to unexpected behavior:

    bug

**How**:
1. Check if founded node is body:
```js
     // in findParent
      if (node === document.body && node.scrollTop === 0) {
        // in chrome body.scrollTop always return 0
        return document.documentElement
      }
```
2. Add some additional checking for case with negative `scrollParentRect.top`

**Checklist**:

- [ ] Documentation N/A
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by souporserious** [comment]
Looks good to me 👍

**Comment by kentcdodds** [comment]
Looks like the build is failing because the code coverage is not 100%

Could you open `coverage/lcov-report/index.html` and see what's missing code coverage and add some tests for this?

Thanks again! This is great!

**Comment by Drapegnik** [comment]
@kentcdodds done!

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by Drapegnik** [comment]
Thank you very much, I am very pleased to be a part of you project! 😃

**Pull request merged**
