### PR TITLE
Update typescript definitions for Downshift components

### PR DESCRIPTION
**Pull request by Jwhiles**
**What**: 
This PR updates the typescript definitions for the Downshift Components props. Specifically it adds type definitions for `selectedItemChanged` `onInputValueChange` and  `onSelect`. It also reorders the type definitions to match how they are presented in the README.md file.

**Why**:
I am currently using Downshift with Typescript in production - and saw type errors when trying to use the onSelect prop. 

**Checklist**:
- [ ] Documentation N/A
- [ ] Tests N/A
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by kentcdodds** [comment]
@vutran and @pbomb :wave:,

Either of you can feel free to Squash and merge PRs without my ✅ on the PR so long as:

1. They're TypeScript/docs only
2. You use "Squash and merge"
3. You ensure the commit message follows our standard format so the release works properly (see MAINTAINING.md). Make sure that the commit message doesn't have "BREAKING CHANGE" in it... That'll publish a major version and we only want to that when there's actually a breaking change :wink:

squash-and-merge

For more complicated changes, I'd prefer to be involved :smile:

**Comment by kentcdodds** [comment]
Hey @Jwhiles! Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by Jwhiles** [comment]
@kentcdodds thanks for adding me. Apologies for the malformed commit messages... I clearly didn't read the guidelines closely enough. 😅

**Comment by kentcdodds** [comment]
Nah, it's not included in `CONTRIBUTING.md` because I think it's silly to ask contributors to follow a commit message when I can change it when merging.

But it _is_ in `other/MAINTAINING.md` because if ya'll are going to merge PRs you need to make sure you do it correctly so we get the proper version released :smile:

**Pull request merged**
