### PR TITLE
added link to Material DownShift Example

### PR DESCRIPTION
**Pull request by nndung179**
This PR related to https://github.com/paypal/downshift/pull/69. I have updated to new version. Also refactor code. Now it looks cleaner.

### CODE REVIEW

**Comment by nndung179** [comment]
Hi @kentcdodds !

Please review it for me.

Thanks!

**Comment by kentcdodds** [comment]
Looks awesome! One thing. It doesn't appear to be using `match-sorter` which I think is great for something like this. More importantly, it doesn't visually show when items are highlighted as I use the up and down arrow keys. I'll merge this, but could you update it so it does that?

**Comment by nndung179** [comment]
Sure. I will update

**Comment by nndung179** [comment]
Hi @kentcdodds 
I added 2 things like you recommended:
+ match sorter
+ highlight item when using key up & down

**Pull request merged**
