### PR TITLE
fix(portal): Prevent reset on touch inside portal

### LINKED ISSUE #485: Menu closes when touching an item inside a menu which is in a portal
- `downshift` version: 2.0.9
- `node` version: 8.9.4
- `npm` (or `yarn`) version: yarn 1.7.0

Relevant code or config

```javascript
<Portal>
  <ul {...getMenuProps()}
    // Items with getItemProps inside
  </ul>
</Portal>
```

What you did: Click on an item inside the menu, which is being rendered inside of a portal.

What happened:

Menu item was not selected and the menu was closed.

Reproduction repository:

N/A - Can create a code sandbox if needed

Problem description:

When touching an item, Downshift determines whether or not to reset based off of `event.target` being contained inside of `this._rootNode`. In this case, the target is outside of `this._rootNode` since it is in a portal.

Suggested solution:

Take `this._menuNode` into account inside of `onTouchStart` in addition to `this._rootNode`.

Relevant code: https://github.com/paypal/downshift/blob/master/src/downshift.js#L937-L945

Relevant issue: #444

### PR DESCRIPTION
**Pull request by green-arrow**
**What**: Prevent resetting downshift when a touch start event occurs within the menu inside of a portal. Fixes #485 

**Why**: Downshift unnecessarily resets when touching anywhere outside of the root node, even if within the menu node.

**How**: Check both root node and menu node on the touch start event.

**Checklist**:

- [ ] Documentation N/A
- [x] Tests
- [x] Ready to be merged
      
- [x] Added myself to contributors table
      

Fixes #485. Related to #444

### CODE REVIEW

**Comment by green-arrow** [comment]
@kentcdodds - This should be good to go. I'm not sure what happened with the CI build. I can't find a good error message in there.

**Comment by kentcdodds** [comment]
I'm not sure what's up with CI. But releases are still going out so 🤷‍♂️ 

If you want to dive in that'd be cool 👌

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Pull request merged**
