### PR TITLE
fix(typings): added typings for stateReducer and Downshift.stateChangeTypes properties

### LINKED ISSUE #338: Provide typings for stateReducer
* `downshift` version: 1.28.0
* `node` version: 8.9.1
* `npm` (or `yarn`) version: yarn 1.3.2

Problem description:

When trying to use the fantastic `stateReducer` property, TypeScript warns that there is no such property in Downshift component.

Suggested solution:

Provide typings for `stateReducer` property.
I can create a PR for that in some time.

### PR DESCRIPTION
**Pull request by Antontelesh**
**What**:

Added TypeScript typings for the fantastic `stateReducer` property as well as `Downshift.stateChangeTypes`.

Don't know if that can be covered with tests.

**Why**:

This fixes #338

**How**:

- split `ControllerStateAndHelpers` into separate interfaces: `DownshiftState`, `PropGetters` and `Actions`
- `ControllerStateAndHelpers` combines the three interfaces above
- added `stateReducer` property to `DownshiftProps`

**Checklist**:

* [ ] Documentation N/A
* [ ] Tests
* [x] Ready to be merged
      
* [x] Added myself to contributors table
      

**Future possible improvements**:

Currently `DownshiftState` is almost repeated in `StateChangeOptions`. I think, the latter can somehow extend the former.

### CODE REVIEW

**Comment by Antontelesh** [comment]
Added types for `Downshift.stateChangeTypes`.

CI is failing as it cannot find `storybook:install` npm script.

**Comment by kentcdodds** [comment]
Yeah, you don't really need to worry about it. But if you want to rebase on master then that should fix it :+1:

**Comment by Antontelesh** [comment]
Rebased

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by Antontelesh** [comment]
Awesome! Thank you, @kentcdodds

**Pull request merged**
