### PR TITLE
make getInputProps accept extra props #313

### PR DESCRIPTION
**Pull request by kristianmandrup**
As per the discussion and examples in [313](https://github.com/paypal/downshift/issues/313#issuecomment-427282033)

### CODE REVIEW

**Comment by kentcdodds** [comment]
I think your editor messed up formatting and you must have skipped the pre-commit hook that fixes it automatically for you. You can reformat it manually via `npx kcd-scripts format`.

**Comment by kristianmandrup** [comment]
Yes, I have my VSC editor configured to use Prettier. I will run the script and make  a new PR. Cheers!

**Comment by kristianmandrup** [comment]
It's a one line fix you could apply in 1-2 mins. 

When trying to run your formatter I get this error:

```
✔ ~/repos/forks/downshift [input-props-types L|✔] 
18:42 $ npx kcd-scripts format
In file included from ../fsevents.cc:6:
../../nan/nan.h:1064:44: warning: 'ToString' is deprecated: Use maybe version [-Wdeprecated-declarations]
      v8::Local<v8::String> string = from->ToString(v8::Isolate::GetCurrent());
                                           ^
/Users/kristianmandrup/.node-gyp/11.0.0/include/node/v8.h:2537:3: note: 'ToString' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/kristianmandrup/.node-gyp/11.0.0/include/node/v8config.h:326:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../fsevents.cc:63:6: warning: field 'async_resource' will be initialized after field 'lockStarted' [-Wreorder]
   : async_resource("fsevents:FSEvents"), lockStarted(false) {
     ^
2 warnings generated.
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreServices.framework/CoreServices.tbd and library file /System/Library/Frameworks//CoreServices.framework/CoreServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork.tbd and library file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.
[error] Invalid configuration file: Cannot find module 'kcd-scripts/prettier'
```

**Comment by kentcdodds** [comment]
I'm guessing you didn't install dependencies. If it's just a 2 line change then maybe you can do it in the github editor instead? I can't see from the diff which of the lines were changed...

**Comment by kristianmandrup** [comment]
Alright, cool, got it sorted. Should be correctly formatted now.

**Comment by kentcdodds** [comment]
Thanks @cassels!

Sorry that this has fallen to the side for people. I guess none of the TS maintainers have been available for review.

@kristianmandrup, I'm afraid the README has a merge conflict (this is probably my biggest frustration with the all-contributors thing as it is today). If you could rebase (don't bother manually fixing up the README, git hooks should fix it automatically), then I'll merge this. Thanks!

**Comment by kristianmandrup** [comment]
@kentcdodds The fix is a one liner. I'm spending way too much time and effort trying to achieve a clean PR on my end. It would be much easier IMO if one of you core guys could paste in the changed line and do the merge proper. Thanks ;)

**Comment by kristianmandrup** [comment]
Very happy it finally got merged :) Good job!!

**Comment by kentcdodds** [comment]
Sorry, but the build is broken. Need to figure out what's wrong. There cannot be a release when the build is broken. 😬

**Comment by johnjesse** [comment]
@kristianmandrup

I've just taken the latest version, and I'm having a few issues,
for instance this one
`Types of property 'value' are incompatible. Type 'string | number | string[] | undefined' is not assignable to 'string | undefined'`

The `string | number | string[] | undefined` is the type of the `value` prop on the interface `React.HTMLProps<HTMLInputElement>`, I also get similar errors for props like default value etc... why did you decide to make this the return type of `getInputProps`, as far as I can tell this function can only return `T` and the values returned here https://github.com/kristianmandrup/downshift/blob/317f541906d3c32692cd0664f826d2750694b766/src/downshift.js#L747-L760
Shouldn't that be typed as a separate interface.

This change has also made the types inconsistent, downshift returns the `inputValue` as the `value`, which is currently typed to be `string | null`   which doesn't correspond to the the type of `value` on `React.HTMLProps<HTMLInputElement>`

Finally, should this have been marked as a breaking change? It makes the types stricter than they were previously which always has the potential to result in breakages

**Comment by kristianmandrup** [comment]
@cassels I couldn't agree more. The intention was to make the types less strict, since the original types blocked this Material UI use case. Ideally the types should allow imposing some structure/rules while allowing flexibility depending on the use case.

Something like the following ("meta style", ie. don't take it literally) `InputProps<T = any, K? = any> (args: T) => K | T` without knowing all the ins and outs of TypeScript generics TBH. 
Your thoughts?

**Comment by johnjesse** [comment]
It would be nicer if the return type of `getInputProps` could be inferred... but I don't see how that could be done. An alternative would be it returns an interface which includes all the bits that are React/ReactNative specific as optional.

@cassels as an example of my issue, in https://github.com/paypal/downshift/blob/master/test/basic.test.tsx add a textInput component as 
```
interface ITextInputProps extends React.HTMLProps<HTMLInputElement> {
  value: string | undefined
}

function TextInput(props: ITextInputProps) {
  return <input {...props} />
}
```
just an input that is stricter in what it's value can be.

Then replace the input in the test with `TextInput`. Unless the component you use `getInputProps` on has  a set of props that exactly matches `React.HTMLProps<HTMLInputElement>` then you will get typings issues

**Pull request merged**
