### PR TITLE
Typescript unused imports

### PR DESCRIPTION
**Pull request by pbomb**
**What**:
* Fix TypeScript compilation error
* Fix eslint error with JSDocs

**Why**:
The Travis CI build is currently broken on these 2 issues.

**How**:
* Add tsconfig to error on unused imports to help identify invalid usages and then removed them
* Added JSDoc `@param` and `@return` declarations

**Checklist**:

- [x] Documentation N/A
- [x] Tests N/A
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thank you!

**Comment by pbomb** [comment]
You're welcome!

**Comment by kentcdodds** [comment]
Thanks again for your help! I've added you as a collaborator on the project. Please make sure that you review the CONTRIBUTING.md file (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by pbomb** [comment]
Cool, thanks! I'll take a look at all those things. Some of these will be new for me.

**Comment by kentcdodds** [comment]
You may also find this useful: https://github.com/paypal/downshift/blob/master/other/MAINTAINING.md

**Pull request merged**
