### PR TITLE
fix autocomplete property #527 

### PR DESCRIPTION
**Pull request by JCofman**
**What**:
Changes Autocomplete attribute to off.

**Why**:
Nope is ignored on current Chrome 67 and Opera 54.

**How**:
Changed the attribute and updated test snapshots

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged
      
- [x] Added myself to contributors table
      

should fix [#527]

### CODE REVIEW

**Comment by kentcdodds** [comment]
Ah, looks like you'll need to update the snapshots. Please see the contributing guidelines to see how to do that. Thanks!

**Comment by kentcdodds** [comment]
Oh, just noticed it's the react-native snapshots which are a tad harder to update. You can run:

```
npm run build
npx jest --config other/react-native --updateSnapshot
```

I think that should do it :) Thank you!

**Comment by kentcdodds** [comment]
Thanks!

**Comment by JCofman** [comment]
Thx @kentcdodds ! :)

**Pull request merged**
